import {
  FaHome,
  FaInfoCircle,
  FaBlog,
  FaBook,
  FaUser,
  FaChartLine,
  FaEnvelope,
  FaCogs,
  FaQuestionCircle,
  FaClipboardList,
} from "react-icons/fa";

export const tabItems = [
  {
    id: "home",
    title: "Home",
    to: "/",
    icon: FaHome,
    pinned: true,
  },
  {
    id: "about",
    title: "About us",
    to: "/about",
    icon: FaInfoCircle,
    pinned: false,
  },
  {
    id: "blog",
    title: "Blog",
    to: "/blog",
    icon: FaBlog,
    pinned: true,
  },
  {
    id: "docs",
    title: "Documentation",
    to: "/docs",
    icon: FaBook,
    pinned: false,
  },
  {
    id: "profile",
    title: "Profile",
    to: "/profile",
    icon: FaUser,
    pinned: true,
  },
  {
    id: "analytics",
    title: "Analytics",
    to: "/analytics",
    icon: FaChartLine,
    pinned: false,
  },
  {
    id: "contact",
    title: "Contact Us",
    to: "/contact",
    icon: FaEnvelope,
    pinned: false,
  },
  {
    id: "settings",
    title: "Settings",
    to: "/settings",
    icon: FaCogs,
    pinned: false,
  },
  {
    id: "faq",
    title: "FAQ",
    to: "/faq",
    icon: FaQuestionCircle,
    pinned: false,
  },
  {
    id: "tasks",
    title: "Tasks",
    to: "/tasks",
    icon: FaClipboardList,
    pinned: false,
  },
];
